site_name: National Genomic Test Directory (NGTD) application
nav:
  - Home: 'README.md'
  - 'User Guide':
    - 'Installation': 'INSTALL.md'
    - 'User guide': 'userguide.md'
  - About:
    - 'License': 'license.md'